apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9065
          env:
            - name: USERS_POSTGRES_DB_HOST
              value: "users-db-service"
            - name: USERS_POSTGRES_DB_PORT_INNER
              value: "5432"
            - name: USERS_POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_USER
            - name: USERS_POSTGRES_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_PASSWORD
            - name: USERS_POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: users-config
