apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: CONFIG_FILE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "users-db"
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      initContainers:
        - name: migrate-db
          image: users-service:latest
          imagePullPolicy: Never
          command: ["/bin/sh", "-c", "/app/users-service/_docker/entrypoint.sh"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "users-db"
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: users-config
