apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: users-service
spec:
  type: ClusterIP
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 9065
      targetPort: 9065
      nodePort: 30065
